export const dataChuongTK = [
    {
        id: 1,
        HocKy: "Học kỳ 1",
        tongTC: 15,
        hocPhanBatBuoc: [
            {
                id: 1,
                maMH: 'INT2201',
                tenMH: 'Cấu trúc dữ liệu và giải thuật',
                maHP: 'INT2201',
                hpTienQuyet: 'INT2201',
                soTC: 3,
                soTietLT: 30,
                soTietTH: 15,
                trangThai: 'Dat',
            },
            {
                id: 2,
                maMH: 'INT2201',
                tenMH: 'Cấu trúc dữ liệu và giải thuật',
                maHP: 'INT2201',
                hpTienQuyet: 'INT2201',
                soTC: 3,
                soTietLT: 30,
                soTietTH: 15,
                trangThai: 'Dat',
            },
            {
                id: 3,
                maMH: 'INT2201',
                tenMH: 'Cấu trúc dữ liệu và giải thuật',
                maHP: 'INT2201',
                hpTienQuyet: 'INT2201',
                soTC: 3,
                soTietLT: 30,
                soTietTH: 15,
                trangThai: 'Dat',
            },
        ],
        hocPhanTuChon: [
            {
                id: 1,
                maMH: 'INT2201',
                tenMH: 'Cấu trúc dữ liệu và giải thuật',
                maHP: 'INT2201',
                hpTienQuyet: 'INT2201',
                soTC: 3,
                soTietLT: 30,
                soTietTH: 15,
                trangThai: 'Dat',
            },
            {
                id: 2,
                maMH: 'INT2201',
                tenMH: 'Cấu trúc dữ liệu và giải thuật',
                maHP: 'INT2201',
                hpTienQuyet: 'INT2201',
                soTC: 3,
                soTietLT: 30,
                soTietTH: 15,
                trangThai: 'Dat',
            },
            {
                id: 3,
                maMH: 'INT2201',
                tenMH: 'Cấu trúc dữ liệu và giải thuật',
                maHP: 'INT2201',
                hpTienQuyet: 'INT2201',
                soTC: 3,
                soTietLT: 30,
                soTietTH: 15,
                trangThai: 'Dat',
            },
        ]
    },
    {
        id: 2,
        HocKy: "Học kỳ 2",
        tongTC: 15,
        hocPhanBatBuoc: [
            {
                id: 1,
                maMH: 'INT2201',
                tenMH: 'Cấu trúc dữ liệu và giải thuật',
                maHP: 'INT2201',
                hpTienQuyet: 'INT2201',
                soTC: 3,
                soTietLT: 30,
                soTietTH: 15,
                trangThai: 'Dat',
            },
            {
                id: 2,
                maMH: 'INT2201',
                tenMH: 'Cấu trúc dữ liệu và giải thuật',
                maHP: 'INT2201',
                hpTienQuyet: 'INT2201',
                soTC: 3,
                soTietLT: 30,
                soTietTH: 15,
                trangThai: 'Dat',
            },
            {
                id: 3,
                maMH: 'INT2201',
                tenMH: 'Cấu trúc dữ liệu và giải thuật',
                maHP: 'INT2201',
                hpTienQuyet: 'INT2201',
                soTC: 3,
                soTietLT: 30,
                soTietTH: 15,
                trangThai: 'Dat',
            },
        ],
        hocPhanTuChon: [
            {
                id: 1,
                maMH: 'INT2201',
                tenMH: 'Cấu trúc dữ liệu và giải thuật',
                maHP: 'INT2201',
                hpTienQuyet: 'INT2201',
                soTC: 3,
                soTietLT: 30,
                soTietTH: 15,
                trangThai: 'Dat',
            },
            {
                id: 2,
                maMH: 'INT2201',
                tenMH: 'Cấu trúc dữ liệu và giải thuật',
                maHP: 'INT2201',
                hpTienQuyet: 'INT2201',
                soTC: 3,
                soTietLT: 30,
                soTietTH: 15,
                trangThai: 'Dat',
            },
            {
                id: 3,
                maMH: 'INT2201',
                tenMH: 'Cấu trúc dữ liệu và giải thuật',
                maHP: 'INT2201',
                hpTienQuyet: 'INT2201',
                soTC: 3,
                soTietLT: 30,
                soTietTH: 15,
                trangThai: 'Dat',
            },
        ]
    },
    {
        id: 3,
        HocKy: "Học kỳ 3",
        tongTC: 15,
        hocPhanBatBuoc: [
            {
                id: 1,
                maMH: 'INT2201',
                tenMH: 'Cấu trúc dữ liệu và giải thuật',
                maHP: 'INT2201',
                hpTienQuyet: 'INT2201',
                soTC: 3,
                soTietLT: 30,
                soTietTH: 15,
                trangThai: 'Dat',
            },
            {
                id: 2,
                maMH: 'INT2201',
                tenMH: 'Cấu trúc dữ liệu và giải thuật',
                maHP: 'INT2201',
                hpTienQuyet: 'INT2201',
                soTC: 3,
                soTietLT: 30,
                soTietTH: 15,
                trangThai: 'Dat',
            },
            {
                id: 3,
                maMH: 'INT2201',
                tenMH: 'Cấu trúc dữ liệu và giải thuật',
                maHP: 'INT2201',
                hpTienQuyet: 'INT2201',
                soTC: 3,
                soTietLT: 30,
                soTietTH: 15,
                trangThai: 'Dat',
            },
        ],
        hocPhanTuChon: [
           
        ]
    }
]